### ISSUE TITLE
AppImage is missing a .DirIcon file

### ISSUE THREAD

**Issue by probonopd** [neopostmodern/wohnungsbot#1]
The AppImage is missing a [`.DirIcon`](https://docs.appimage.org/reference/appdir.html) file.

Possibly this is an electron-builder issue?

Reference:
https://github.com/AppImage/appimage.github.io/pull/1646

**Comment by neopostmodern** [comment]
I don't really understand what happened to the issue you mentioned (https://github.com/electron-userland/electron-builder/issues/3988) -- do I just need to update `electron-builder`? Or is it something to be applied manually? (If so, a PR would be very welcome since you seem to understand what the underlying issue is about. Otherwise I'll read into this in a week or two.)

**Comment by probonopd** [comment]
I think this will be fixed in the next electron-builder release, once it becomes available and once this project is updated to use that electron-builder version. Thanks for your consideration!

**Comment by neopostmodern** [comment]
@probonopd — could you please check if this is fixed in the latest release? https://github.com/neopostmodern/wohnungsbot/releases/tag/v1.1.0

**Comment by probonopd** [comment]
Unfortunately the issue persists:
https://travis-ci.org/AppImage/appimage.github.io/builds/587795188#L255-L280
