### ISSUE TITLE
bot stuck after solving captcha (linux)

### ISSUE THREAD

**Issue by fischer-hub** [neopostmodern/wohnungsbot#109]
After solving the captcha the bot gets stuck at "ich übernehme wieder" (or whatever the line was), with terminal output:

```
isElementInViewport([data-id="134351017"]) called on non-existent element
isElementInViewport([data-id="134351076"]) called on non-existent element
```
However, resetting the bot with the "bot zurücksetzen" button fixes the issue. This also doesn't seem to happen after every solved captcha.

**Comment by drblaui** [comment]
I have this issue too and i believe that the isElementInViewport function has nothing to do with it but rather is an artefact from when the bot actively searched for flats.

However this problem arises everytime I solve a captcha. The bot will not continue after I solve it

**Comment by neopostmodern** [comment]
I just tested it on an Ubuntu 20.04 machine and (albeit only after a minute or so) the bot continued to do what it was supposed to after I solved the captcha.
The log output you're referring to is something (unfortunately) ubiquitous that comes up all the time and doesn't in itself yield much information. Can you describe more of the context when this happens? Was the bot already performing applications before? Did you solve the captcha only after the bot waited for a long time for you?
There seems to be something behind this since it happened to two of you independently, but it seems to be non-trivial.

**Comment by neopostmodern** [comment]
Now that 1.7 is being released I'm closing a bunch of issues that could not be linked to specific causes. Please try with the latest version and if the error still happens, re-open this issue with more details.
