### ISSUE TITLE
Filter Keywords

### ISSUE THREAD

**Issue by pcace** [neopostmodern/wohnungsbot#36]
Hi, is there any way to filter Keywords? 
For Example filter out "WBS" or "Tauschwohnung"... It really would help to specify what not to look for...

Cheers and Thanks for that great Software!

**Comment by neopostmodern** [comment]
There is an option for "WBS" exclusion already, by default it should exclude WBS-only flats. If this doesn't work, please open another issue.

"Tauschwohnung" is tracked in #30, PRs very welcome. See #29 also.

I think the UX is much better if there is a checkable option for each keyword instead of requiring users to compile their own keyword lists (which would require an entire regex-like system for "any of these", "all of these", "whitelist"...).
