### ISSUE TITLE
Execute customizable (shell) script after application

### ISSUE THREAD

**Issue by pcace** [neopostmodern/wohnungsbot#37]
Hi, is there any way to fire up an individual shell script after each successful application?
what would be the easiest way?

Thanks a lot!

PS.: i hat an other flathunter running, wich would send me telegram messages including the pdf. I really would like to have this feature here too. Any chance?

**Comment by neopostmodern** [comment]
**Shell script**  
I'm quite sure it would be possible to store either an entire shell script or a command to be executed after each application (and then pass in if it was successful or not, which I figure would be more versatile) — but, it's nothing I'm personally interested in adding, since the software is not targeted at pro users ([context](https://media.ccc.de/v/36c3-10988-wohnungsbot_an_automation-drama_in_three_acts)). I'd be happy to merge a comprehensible PR though, I don't want to hinder pro users.

**Telegram**  
You can check the option to get an e-mail sent (admittedly without the PDF attachment, that might be nice). IMHO this covers the use case you mention, without getting into closed platforms.

**Comment by pcace** [comment]
Thank you so much for your fast reply! 
I will look into the script thing... 
Telegram: Sending the PDF really would help!

**Comment by neopostmodern** [comment]
I've updated the README to give devs an easier start. :rocket:

Attaching the PDF [looks pretty easy](https://github.com/sendgrid/sendgrid-nodejs/blob/master/docs/use-cases/attachments.md), but I won't get to it in the next month unfortunately.
